config/routes.rb
Rails.application.routes.draw do
  resources :reports, only: %i[index create new show delete]
  resources :invoices, only: %i[index create new]
  resources :packages, only: %i[index create new]
  resources :csv, only: %i[show]
  root 'reports#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  # TODO: add a user/client model to scope the invoices by user
  has_many :packages, dependent: :destroy
  enum invoice_type: %i[ups fedex usps]
end

app/models/package.rb
class Package < ActiveRecord::Base
  belongs_to :invoice, dependent: :destroy
end

app/models/report.rb
class Report < ActiveRecord::Base
  # use active storage to store generated csv file
  # todo: configured with amazon s3
  has_one_attached :csv_download

  enum status: %i[pending completed error], _prefix: :status

  default_scope { where(is_deleted: false) }

  # override destroy method to soft delete report
  def destroy
    update_attribute :is_deleted, true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/csv_controller.rb
class CsvController < ApplicationController
  # Endpoint to kick off worker to generate report and save to active storage/s3
  # If success, will update the status from pending to complete
  # Possibly we can incoporate action cable or pusher to notify user a report is completed
  def show
    if ::CsvReportWorker.perform_async(params[:id])
      redirect_to reports_url
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.all
  end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoice_params)
    if @invoice.save
      redirect_to invoices_url
    else
      render action: 'new'
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:invoice_amount, :invoice_date, :invoice_number, :invoice_type, :reference_number)
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def index
    @packages = Package.all
  end

  def new
    @package = Package.new
  end

  def create
    @package = Package.new(package_params)
    if @package.save
      redirect_to packages_url
    else
      render action: 'new'
    end
  end

  private

  def package_params
    params.require(:package).permit(:tracking_number, :service_name, :ship_date, :delivery_date, :expected_delivery_date, :invoice_id)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def show
    # Generate a preview of the reports
    report = Report.find(params[:id])
    @reports = ::ReportGenerator.new(report).perform
  end

  def new
    @report = Report.new
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      redirect_to reports_url
    else
      render action: 'new'
    end
  end

  private

  def report_params
    params.require(:report).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_helper.rb
module CsvHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/invoices/index.html.erb
<h1>My Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Invoice Type</th>
      <th>Invoice Date</th>
      <th>Invoice Amount</th>
      <th>Reference Number</th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.invoice_type %></td>
        <td><%= invoice.invoice_date %></td>
        <td><%= invoice.invoice_amount %></td>
        <td><%= invoice.reference_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Invoice", new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= form_for @invoice, url: {action: "create"} do |f| %>
  <%= f.collection_radio_buttons :invoice_type, Invoice.invoice_types, :first, :first %><br />
  <%= f.date_field :invoice_date %>
  <%= label :invoice_date, 'Invoice Date' %><br />
  <%= f.number_field :invoice_amount %>
  <%= label :invoice_amount, 'Invoice Amount'%><br />
  <%= f.text_field :reference_number %>
  <%= label :reference_number, 'Reference Number'%><br />
  <%= f.submit "Create Invoice" %>
<% end %>

<%= link_to 'Back to Invoices', invoices_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShipmentReportsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/index.html.erb
<h1>Report Lists</h1>

<table>
  <thead>
    <tr>
      <th>Report Status</th>
      <th>Invoice Start Date</th>
      <th>Invoice End Date</th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.status %></td>
        <td><%= report.start_date %></td>
        <td><%= report.end_date %></td>
        <td><%= link_to "Preview", report %></td>
        <td><%= link_to 'Delete', report,
          data: { confirm: 'Are you sure?' }, method: :delete %></td>
        <td><%= link_to 'download', rails_blob_path(report.csv_download,
          disposition: "attachment") if report.csv_download.attached? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Report", new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= form_for @report, url: { action: 'create' } do |f| %>
  <%= f.date_field :start_date %>
  <%= label :start_date, 'Start Invoice Date' %><br />
  <%= f.date_field :end_date %>
  <%= label :end_date, 'End Invoice Date' %><br />
  <%= f.submit "Generate Report" %>
<% end %>

<%= link_to 'Back to Reports', reports_url %>

app/views/reports/show.html.erb
<h1>Invoice Summary Report</h1>

<table>
  <thead>
    <tr>
      <th>Invoice Type</th>
      <th>Invoice Date</th>
      <th>Invoice Amount</th>
      <th>Invoice Reference Number</th>
      <th>Number of Packages</th>
      <th>Number of Unique Services</th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.invoice_type %></td>
        <td><%= report.invoice_date %></td>
        <td><%= report.invoice_amount %></td>
        <td><%= report.invoice_reference_number %></td>
        <td><%= report.number_of_packages %></td>
        <td><%= report.number_of_unique_service_names %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Generate Repport(CSV)", csv_path %>

<%= link_to "Back to Reports", reports_url %>